apiVersion: v1
kind: Secret
metadata:
  name: money-movement-mysql-root-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bW9uZXktbW92ZW1lbnQtcm9vdC1wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: money-movement-mysql-credentials
type: Opaque
data:
  MYSQL_USER: bW9uZXktbW92ZW1lbnQtdXNlcg==
  MYSQL_PASSWORD: bW9uZXktbW92ZW1lbnQtdXNlci1wYXNzd29yZA==
