apiVersion: v1
kind: Service
metadata:
  name: money-movement-mysql-service
  labels:
    app: money-movement-mysql
spec:
  clusterIP: None
  selector:
    app: money-movement-mysql
  ports:
    - port: 3306
      name: money-movement-mysql
