apiVersion: batch/v1
kind: Job
metadata:
  name: money-movement-migrate-seed
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: money-movement-migrate-seed
          image: dbharti001/money-movement-nodejs:1.0.0
          command: ["node", "build/scripts/seed.js"]
          envFrom:
            - configMapRef:
                name: money-movement-config
            - configMapRef:
                name: money-movement-mysql-config
            - secretRef:
                name: money-movement-mysql-credentials
