apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-movement
  labels:
    app: money-movement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: money-movement
  template:
    metadata:
      labels:
        app: money-movement
    spec:
      containers:
        - name: money-movement
          image: dbharti001/money-movement-nodejs:1.0.0
          envFrom:
            - configMapRef:
                name: money-movement-config
            - configMapRef:
                name: money-movement-mysql-config
            - secretRef:
                name: money-movement-mysql-credentials
