apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  NODE_ENV: "development"
  SMTP_HOST: "mailpit-service"
  SMTP_PORT: "1025"
  SENDER_EMAIL: "payments@node-payment-micro.local"
  KAFKA_BROKERS: "kafka-0.kafka-service:9092,kafka-1.kafka-service:9092"
