apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  NODE_ENV: "development"
  SERVER_PORT: "1337"
  AUTH_GRPC_HOSTNAME: "auth-service"
  AUTH_GRPC_PORT: "9000"
  MONEY_MOVEMENT_GRPC_HOSTNAME: "money-movement-service"
  MONEY_MOVEMENT_GRPC_PORT: "9000"
