apiVersion: v1
kind: Service
metadata:
  name: ledger-mysql-service
  labels:
    app: ledger-mysql
spec:
  clusterIP: None
  selector:
    app: ledger-mysql
  ports:
    - port: 3306
      name: ledger-mysql
