apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql-root-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YXV0aC1yb290LXBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-mysql-credentials
type: Opaque
data:
  MYSQL_USER: YXV0aC11c2Vy
  MYSQL_PASSWORD: YXV0aC11c2VyLXBhc3N3b3Jk
